pipeline:
  docker:
    image: plugins/docker
    repo: dodoreg.azurecr.io/exporter/redis
    tags: drone-io-test
    registry: dodoreg.azurecr.io
    secrets: [ docker_username, docker_password ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock