name: Build

on:
  push:
    # branches:
      # - master

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Push to master
    runs-on: ubuntu-latest
    env:
        REPO_ORIGIN_VERSION: "1.12.1"
        RELEASE_TAG: "${ REPO_ORIGIN_VERSION }.${{ github.run_number }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./docker/Dockerfile.amd64
          tags: |
            dodopizza/redis_exporter:latest
            dodopizza/redis_exporter:${ REPO_ORIGIN_VERSION }
            dodopizza/redis_exporter:${ RELEASE_TAG }
          build-args: |
            SHA1=${{ github.sha }}
            TAG=${ RELEASE_TAG }

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${ RELEASE_TAG }
          release_name: Release v${ RELEASE_TAG }
          draft: false
          prerelease: false
